apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bookshop-config-service
  name: bookshop-config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookshop-config-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bookshop-config-service
    spec:
      containers:
      - image: ghcr.io/bladespring/bookshop-config-service:0.0.1
        name: bookshop-config-service
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 5"]
        resources: {}
status: {}
