apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bookshop-config-service
  name: bookshop-config-service
spec:
  ports:
  - name: 80-8888
    port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: bookshop-config-service
  type: ClusterIP
status:
  loadBalancer: {}
